### ISSUE TITLE
请问为什么本论文中 imvoxelnet 的结果与原始 DAIR-V2X 库中对应的结果差距很大

### ISSUE THREAD

**Issue by rbldrbld** [Bosszhe/VIMI#3]
本论文中：
![image](https://github.com/Bosszhe/VIMI/assets/49875147/bd19ec3c-08b6-4a8e-9a65-643708fa0738)
DAIR-V2X中：
https://github.com/AIR-THU/DAIR-V2X/tree/c65a55617f7d0a9b78dc9d107370c95bcac55dca/configs/vic3d/late-fusion-image/imvoxelnet
![image](https://github.com/Bosszhe/VIMI/assets/49875147/548fb23a-0600-4173-8e13-20a438abab9d)

**Comment by Bosszhe** [comment]
The label for training is different from the paper DAIR-V2X. In the DAIR-V2X-C, there are three types of labels: Single Vehicle,  Single Infrastructure, and Cooperative Label. The LF baseline in the paper uses Single Vehicle and Single Infrastructure Label to train Veh-Only and Inf-Only Models and evaluate with Cooperative Label.
For VIMI, we assume that there is only one ground truth in the world so that all experiments are trained and evaluated on Cooperative Label. For a fair comparison, we processed Cooperative Label and did the same exps of veh-only, inf-only, and late-fusion.(The label processing can be seen in the figure.)
![屏幕截图 2023-12-19 162557](https://github.com/Bosszhe/VIMI/assets/34713622/8868036f-b9f6-45d5-8888-88472e4e3620)

**Comment by rbldrbld** [comment]
好的 感谢您的及时回复

**Comment by rbldrbld** [comment]
> The label for training is different from the paper DAIR-V2X. In the DAIR-V2X-C, there are three types of labels: Single Vehicle, Single Infrastructure, and Cooperative Label. The LF baseline in the paper uses Single Vehicle and Single Infrastructure Label to train Veh-Only and Inf-Only Models and evaluate with Cooperative Label. For VIMI, we assume that there is only one ground truth in the world so that all experiments are trained and evaluated on Cooperative Label. For a fair comparison, we processed Cooperative Label and did the same exps of veh-only, inf-only, and late-fusion.(The label processing can be seen in the figure.) ![屏幕截图 2023-12-19 162557](https://private-user-images.githubusercontent.com/34713622/291526193-8868036f-b9f6-45d5-8888-88472e4e3620.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMxNDc4MDAsIm5iZiI6MTcwMzE0NzUwMCwicGF0aCI6Ii8zNDcxMzYyMi8yOTE1MjYxOTMtODg2ODAzNmYtYjlmNi00NWQ1LTg4ODgtODg0NzJlNGUzNjIwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIxVDA4MzE0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBlY2M5YWVmYmU5YWVkMmIwNmI1ZTMyNDkxMWYyMGEyMjVjNjQxNTA5ZTRlNTUxNmM4MzUzNGViNjYwZDYzOWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.FkwWcCop8iy3EvY21I3WBiX3MI95oCwtVjZlSjfQU_k)

请问vimi是否使用了where2comm中提供的补充标注文件
